### ISSUE TITLE
Unix new lines

### ISSUE THREAD

**Issue by richard-mihalovic** [artifacthealth/hl7parser#2]
When I use `hl7parser.create(...)` on MacOS it can't parse the text / file if there are Unix line endings `\n`. If I convert the line endings to `\n -> \r\n` it works.

Maybe it will be good to have some line ending detection support to parse the texts also with Unix line endings.

**Comment by meirgottlieb** [comment]
Hey @richard-mihalovic. The issue is not Unix vs Windows. If you take a look at the [HL7 transport spec](http://www.hl7.org/documentcenter/public_temp_07942107-1C23-BA17-0C825327B9558C1F/wg/inm/mllp_transport_specification.PDF), HL7 messages use carriage return `\r` for segment delineation. However, I understand for testing purposes it is helpful to load message from a file. I'll add an option to use non-standard segment delineators. In the meantime, you should convert `\n -> \r` not `\n -> \r]n`.

**Comment by richard-mihalovic** [comment]
Thank you for your explanation. 

It took me some time to find out the reason why the parser returned an empty node. Maybe it will be helpful to display some warning, that the HL7 message doesn't contain any `\r` character.
